### ISSUE TITLE
TLC website is outdated

### ISSUE THREAD

**Issue by Zimmi48** [charguer/tlc#1]
When looking for "TLC Coq" on Google, the website https://www.chargueraud.org/softs/tlc/ comes first. But this website is outdated: it points to the Inria GitLab repository and claims the library is distributed under the LGPL. In addition to fixing the webpage, the former repository's README should be updated to point to the new location prominently.

**Comment by charguer** [comment]
Fixed, thanks for pointing it out.

**Comment by Zimmi48** [comment]
Great, what about also marking the old repo as deprecated for people who still have the old URL?
